# Generated by Django 5.2.17 on 2026-08-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('planned_sessions', models.PositiveSmallIntegerField(default=0)),
                ('completed_sessions', models.PositiveSmallIntegerField(default=0)),
                ('difficulty', models.PositiveSmallIntegerField(help_text='1 (too easy) - 10 (too hard)')),
                ('energy', models.PositiveSmallIntegerField(help_text='1 (very low) - 10 (very high)')),
                ('recovery', models.PositiveSmallIntegerField(help_text='1 (poor) - 10 (excellent)')),
                ('pain_flag', models.BooleanField(default=False)),
                ('pain_details', models.TextField(blank=True)),
                ('sessions_too_long', models.BooleanField(default=False)),
                ('enjoyment', models.PositiveSmallIntegerField(blank=True, help_text='1-10', null=True)),
                ('disliked_exercises', models.CharField(blank=True, max_length=255)),
                ('performance_change', models.CharField(blank=True, choices=[('better', 'Better'), ('same', 'About the same'), ('worse', 'Worse')], max_length=20)),
                ('barrier_to_completion', models.TextField(blank=True, help_text='What prevented completing sessions, if anything')),
                ('recommendation', models.CharField(blank=True, max_length=30)),
                ('recommendation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins', to='programs.program')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('perceived_difficulty', models.PositiveSmallIntegerField(blank=True, help_text='RPE 1-10 for the session as a whole', null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='programs.workoutday')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
