# Generated by Django 5.2.17 on 2026-09-05 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='avg_workout_bpm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: average heart rate during sessions, if you track it', null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='resting_bpm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Optional: resting heart rate, if you track it', null=True),
        ),
    ]
