# Generated by Django 5.2.17 on 2026-10-08 20:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_alter_workout_options_workout_section_order'),
        ('progress', '0002_checkin_avg_workout_bpm_checkin_resting_bpm'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('user', 'program', 'week_number')},
        ),
    ]
