# Generated by Django 5.2.17 on 2026-08-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed'), ('blocked', 'Blocked — needs professional evaluation')], default='in_progress', max_length=20)),
                ('has_current_pain_or_injury', models.BooleanField(blank=True, null=True)),
                ('pain_or_injury_details', models.TextField(blank=True)),
                ('has_medical_condition_affecting_exercise', models.BooleanField(blank=True, null=True)),
                ('medical_condition_details', models.TextField(blank=True)),
                ('has_cardiovascular_symptoms', models.BooleanField(blank=True, help_text='Chest pain/pressure, irregular heartbeat, etc. during activity', null=True)),
                ('has_dizziness_or_fainting', models.BooleanField(blank=True, null=True)),
                ('has_unusual_shortness_of_breath', models.BooleanField(blank=True, null=True)),
                ('has_prior_exercise_restrictions', models.BooleanField(blank=True, null=True)),
                ('exercise_restriction_details', models.TextField(blank=True)),
                ('had_recent_surgery_or_injury', models.BooleanField(blank=True, null=True)),
                ('recent_surgery_details', models.TextField(blank=True)),
                ('other_safety_concern', models.TextField(blank=True)),
                ('safety_cleared', models.BooleanField(blank=True, help_text='Result of the safety validator. Null until evaluated.', null=True)),
                ('safety_flags', models.JSONField(blank=True, default=list)),
                ('wake_time', models.TimeField(blank=True, null=True)),
                ('sleep_time', models.TimeField(blank=True, null=True)),
                ('sleep_duration_hours', models.FloatField(blank=True, null=True)),
                ('occupation_schedule', models.CharField(blank=True, choices=[('desk_fixed', 'Desk job, fixed hours'), ('desk_flexible', 'Desk job, flexible hours'), ('student', 'Student'), ('on_feet', 'On my feet most of the day'), ('physical_labor', 'Physical labor'), ('shift_work', 'Shift work / irregular'), ('unemployed_home', 'Not currently working / home')], max_length=30)),
                ('sedentary_hours_per_day', models.FloatField(blank=True, null=True)),
                ('daily_activity_level', models.CharField(blank=True, choices=[('very_low', 'Very low — mostly sitting'), ('low', 'Low — light walking'), ('moderate', 'Moderate — regularly on my feet'), ('high', 'High — physically active job/life')], max_length=20)),
                ('meals_per_day', models.PositiveIntegerField(blank=True, null=True)),
                ('meal_schedule_consistency', models.CharField(blank=True, choices=[('consistent', 'Consistent'), ('somewhat', 'Somewhat consistent'), ('irregular', 'Irregular')], max_length=20)),
                ('stress_level', models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very high')], max_length=20)),
                ('schedule_consistency', models.CharField(blank=True, choices=[('very_consistent', 'Very consistent'), ('somewhat', 'Somewhat variable'), ('unpredictable', 'Unpredictable')], max_length=20)),
                ('available_workout_windows', models.CharField(blank=True, help_text='Comma-separated free-text windows, e.g. "early morning, evening"', max_length=255)),
                ('primary_goal', models.CharField(blank=True, choices=[('fat_loss', 'Fat loss'), ('muscle_gain', 'Muscle gain'), ('strength', 'Strength'), ('endurance', 'Endurance'), ('general_fitness', 'General fitness'), ('mobility', 'Mobility'), ('maintenance', 'Maintenance')], max_length=30)),
                ('secondary_goals', models.JSONField(blank=True, default=list)),
                ('training_experience', models.CharField(blank=True, choices=[('none', 'None / never trained'), ('under_6mo', 'Under 6 months'), ('6mo_2y', '6 months – 2 years'), ('2y_5y', '2 – 5 years'), ('5y_plus', '5+ years')], max_length=20)),
                ('past_training_frequency_per_week', models.PositiveIntegerField(blank=True, null=True)),
                ('past_training_type', models.CharField(blank=True, max_length=255)),
                ('time_since_last_trained', models.CharField(blank=True, choices=[('currently_training', 'Currently training'), ('under_1mo', 'Less than a month ago'), ('1_6mo', '1 – 6 months ago'), ('6mo_2y', '6 months – 2 years ago'), ('2y_plus', 'More than 2 years ago'), ('never', 'Never')], max_length=20)),
                ('familiar_exercises', models.TextField(blank=True, help_text='Comma-separated')),
                ('reason_stopped', models.TextField(blank=True)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('deconditioned_beginner', 'Deconditioned Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=30)),
                ('walking_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('walking_pace', models.CharField(blank=True, choices=[('slow', 'Slow'), ('moderate', 'Moderate'), ('brisk', 'Brisk'), ('fast', 'Fast/can jog')], max_length=20)),
                ('stair_tolerance', models.CharField(blank=True, choices=[('poor', 'Struggle with 1 flight'), ('fair', 'OK with 1-2 flights'), ('good', 'OK with 3+ flights'), ('very_good', 'No issue, several flights')], max_length=20)),
                ('sit_to_stand_reps_30s', models.PositiveIntegerField(blank=True, help_text='Reps in 30 seconds', null=True)),
                ('squat_variation', models.CharField(blank=True, choices=[('none', "Can't squat comfortably"), ('assisted', 'Assisted / partial range'), ('bodyweight', 'Full bodyweight squat'), ('loaded', 'Loaded squat')], max_length=20)),
                ('pushup_variation', models.CharField(blank=True, choices=[('none', "Can't do a push-up"), ('wall_incline', 'Wall / incline push-up'), ('knee', 'Knee push-up'), ('full', 'Full push-up'), ('advanced', 'Advanced variation')], max_length=20)),
                ('plank_hold_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('mobility_balance_rating', models.CharField(blank=True, choices=[('poor', 'Poor'), ('fair', 'Fair'), ('good', 'Good'), ('very_good', 'Very good')], max_length=20)),
                ('perceived_exertion_after_tests', models.PositiveIntegerField(blank=True, help_text='RPE 1-10 after the fitness tests', null=True)),
                ('strength_capacity', models.FloatField(blank=True, null=True)),
                ('cardio_capacity', models.FloatField(blank=True, null=True)),
                ('work_capacity', models.FloatField(blank=True, null=True)),
                ('mobility_score', models.FloatField(blank=True, null=True)),
                ('balance_score', models.FloatField(blank=True, null=True)),
                ('training_location', models.CharField(blank=True, choices=[('home_no_equip', 'Home, no equipment'), ('home_some_equip', 'Home, some equipment'), ('gym', 'Gym'), ('outdoor', 'Outdoor'), ('mixed', 'Mixed')], max_length=20)),
                ('available_equipment', models.JSONField(blank=True, default=list)),
                ('days_per_week_available', models.PositiveIntegerField(blank=True, null=True)),
                ('minutes_per_session', models.PositiveIntegerField(blank=True, null=True)),
                ('preferred_workout_time', models.CharField(blank=True, choices=[('early_morning', 'Early morning'), ('morning', 'Morning'), ('midday', 'Midday'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('late_night', 'Late night'), ('varies', 'Varies')], max_length=20)),
                ('exercise_preferences', models.TextField(blank=True, help_text='Comma-separated, free text')),
                ('exercises_to_avoid', models.TextField(blank=True, help_text='Comma-separated, free text')),
                ('training_phase', models.CharField(blank=True, choices=[('phase1', 'Phase 1 — Habit & Tolerance'), ('phase2', 'Phase 2 — Foundation'), ('phase3', 'Phase 3 — Development'), ('phase4', 'Phase 4 — Specialized')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
