# Generated by Django 5.2.17 on 2026-08-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('movement_pattern', models.CharField(choices=[('squat', 'Squat'), ('hinge', 'Hinge'), ('lunge', 'Lunge'), ('push_horizontal', 'Horizontal push'), ('push_vertical', 'Vertical push'), ('pull_horizontal', 'Horizontal pull'), ('pull_vertical', 'Vertical pull'), ('core', 'Core / anti-rotation'), ('carry', 'Carry'), ('gait', 'Gait / locomotion'), ('mobility', 'Mobility / stretch'), ('balance', 'Balance')], max_length=20)),
                ('muscle_groups', models.JSONField(default=list, help_text='List of muscle group codes')),
                ('equipment', models.CharField(choices=[('none', 'No equipment'), ('dumbbells', 'Dumbbells'), ('barbell', 'Barbell'), ('resistance_bands', 'Resistance bands'), ('kettlebell', 'Kettlebell'), ('pullup_bar', 'Pull-up bar'), ('bench', 'Bench'), ('full_gym', 'Full gym access'), ('cardio_machine', 'Cardio machine')], default='none', max_length=20)),
                ('difficulty', models.PositiveSmallIntegerField(choices=[(1, 'Very easy / regression'), (2, 'Beginner'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Very advanced')], default=2)),
                ('exercise_type', models.CharField(choices=[('warmup', 'Warm-up'), ('main_strength', 'Main strength'), ('accessory', 'Accessory'), ('cardio', 'Cardio'), ('mobility', 'Mobility / cooldown'), ('core', 'Core')], default='main_strength', max_length=20)),
                ('instructions', models.TextField(blank=True)),
                ('default_sets', models.PositiveSmallIntegerField(default=3)),
                ('default_reps', models.CharField(blank=True, help_text='e.g. "8-12" or blank if duration-based', max_length=30)),
                ('default_duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('default_rest_seconds', models.PositiveIntegerField(default=60)),
                ('is_low_impact', models.BooleanField(default=True)),
                ('is_beginner_safe', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Free-text tags, e.g. "running", "hiit"')),
                ('progressions', models.ManyToManyField(blank=True, related_name='regressions_of', to='exercises.exercise')),
            ],
            options={
                'ordering': ['exercise_type', 'movement_pattern', 'difficulty'],
            },
        ),
    ]
