# Generated by Django 5.2.17 on 2026-08-30 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('exercises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('goal', models.CharField(blank=True, max_length=30)),
                ('phase', models.CharField(choices=[('phase1', 'Phase 1 — Habit & Tolerance'), ('phase2', 'Phase 2 — Foundation'), ('phase3', 'Phase 3 — Development'), ('phase4', 'Phase 4 — Specialized')], max_length=20)),
                ('difficulty', models.CharField(blank=True, max_length=30)),
                ('days_per_week', models.PositiveSmallIntegerField()),
                ('duration_weeks', models.PositiveSmallIntegerField(default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programs', to='assessment.assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_index', models.PositiveSmallIntegerField(help_text='0=Monday .. 6=Sunday')),
                ('label', models.CharField(blank=True, max_length=100)),
                ('day_type', models.CharField(choices=[('training', 'Training'), ('active_recovery', 'Active recovery'), ('rest', 'Rest')], default='training', max_length=20)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.program')),
            ],
            options={
                'ordering': ['day_index'],
                'unique_together': {('program', 'day_index')},
            },
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('warmup', 'Warm-up'), ('main', 'Main'), ('accessory', 'Accessory'), ('cardio', 'Cardio'), ('cooldown', 'Cool-down / mobility')], default='main', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(blank=True, max_length=30)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('intensity_target', models.CharField(blank=True, help_text='e.g. "RPE 6-7", "conversational pace", "RIR 2-3"', max_length=60)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workouts', to='exercises.exercise')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='programs.workoutday')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
    ]
