# Generated by Django 5.2.17 on 2026-10-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['section_order', 'order']},
        ),
        migrations.AddField(
            model_name='workout',
            name='section_order',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
